{"additions": 6, "auther_ref": "psutil-566", "auther_sha": "9de0f5eccfa4fd86c959a14763b325bdfc3ac406", "author": "amaltaro", "body": "Bump psutil in order to fix the following moderate severity vulnerability:\r\n```\r\nCVE-2019-18874\r\nVulnerable versions: <= 5.6.5\r\nPatched version: 5.6.6\r\n\r\npsutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.\r\n```\r\n\r\nAlso created a python3 spec file.\r\n\r\nNot tested in my private VM.", "branch": "comp_gcc630", "changed_files": 2, "comments": 1, "commits": 1, "created_at": "1584189776", "deletions": 1, "labels": [], "number": 5646, "release-notes": [], "review_comments": 0, "state": "open", "title": "Bump python psutil to 5.6.6", "updated_at": "1584190803", "user": "amaltaro"}